version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      DB_CLUSTER: "maksuamet"
      DB_HOST: "mongo"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
