version: "3.3"
services:
  mongo:
    image: mongo:4.4
    volumes:
      - mongo_conf:/data/configdb
      - mongo_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    restart: always
    networks:
      - maksuamet_net
  api:
    depends_on:
      - mongo
    build:
      context: ../maksuamet
      args:
        BUILD_TIME_ARGUMENT: ${APP_VERSION}
    image: maksuamet-api
    ports:
      - "8001"
    environment:
      DB_USER: ${DB_USER}
      DB_USER_PWD: ${DB_USER_PWD}
      DB_HOST: mongo
      DB_CLUSTER: maksuamet
    networks:
      - maksuamet_net
  web:
    depends_on:
      - api
    build:
      context: ../maksuamet-fe
    image: maksuamet-web
    ports:
      - "8080:80"
      - "8001:8001"
    restart: always
    environment:
      API_URL: http://api:8001
      USER_KOOR: ${USER_KOOR}
      USER_ADMIN: ${USER_ADMIN}
    links:
      - api
    networks:
      - maksuamet_net
volumes:
  mongo_data: {}
  mongo_conf: {}
networks:
  maksuamet_net:
    driver: bridge

