version: "2"
services:
  api:
    image: maksuamet-api
    ports:
      - "8001:8001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data-db
    ports:
      - "27017:27017"
